# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ticketutils}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Fortuna"]
  s.date = %q{2011-06-03}
  s.description = %q{TicketUtils.com client for using thier API}
  s.email = %q{adam@envylabs.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/ticketutils.rb",
    "lib/ticketutils/base.rb",
    "lib/ticketutils/error.rb",
    "lib/ticketutils/seating_chart.rb",
    "lib/ticketutils/venue.rb",
    "spec/fixtures/seating_charts/find.yml",
    "spec/fixtures/seating_charts/find_recent.yml",
    "spec/fixtures/seating_charts/for_venue.yml",
    "spec/fixtures/venues/find.yml",
    "spec/fixtures/venues/find_page_2.yml",
    "spec/fixtures/venues/find_per_page_50.yml",
    "spec/fixtures/venues/find_recent.yml",
    "spec/shared/seating_chart_examples.rb",
    "spec/shared/setup_token.rb",
    "spec/shared/vcr.rb",
    "spec/shared/venue_examples.rb",
    "spec/spec_helper.rb",
    "spec/ticketutils/seating_chart_spec.rb",
    "spec/ticketutils/venue_spec.rb",
    "ticketutils.gemspec"
  ]
  s.homepage = %q{http://github.com/adamfortuna/ticketutils}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{TicketUtils.com client using their API}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<vcr>, ["~> 1.10"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<will_paginate>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<vcr>, ["~> 1.10"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<will_paginate>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<vcr>, ["~> 1.10"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<will_paginate>, [">= 0"])
  end
end

